/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.datosGob.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.docs.datosGob.model.Coleccion;
import com.liferay.docs.datosGob.model.ColeccionModel;
import com.liferay.docs.datosGob.model.ColeccionSoap;

import com.liferay.petra.string.StringBundler;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Coleccion service. Represents a row in the &quot;DB_Coleccion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ColeccionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ColeccionImpl}.
 * </p>
 *
 * @author liferay
 * @see ColeccionImpl
 * @see Coleccion
 * @see ColeccionModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ColeccionModelImpl extends BaseModelImpl<Coleccion>
	implements ColeccionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a coleccion model instance should use the {@link Coleccion} interface instead.
	 */
	public static final String TABLE_NAME = "DB_Coleccion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "homepage", Types.VARCHAR },
			{ "titulo", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("homepage", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("titulo", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table DB_Coleccion (uuid_ VARCHAR(75) null,groupId LONG,homepage VARCHAR(75) not null primary key,titulo VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DB_Coleccion";
	public static final String ORDER_BY_JPQL = " ORDER BY coleccion.homepage ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DB_Coleccion.homepage ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.docs.datosGob.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.docs.datosGob.model.Coleccion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.docs.datosGob.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.docs.datosGob.model.Coleccion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.docs.datosGob.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.docs.datosGob.model.Coleccion"),
			true);
	public static final long GROUPID_COLUMN_BITMASK = 1L;
	public static final long UUID_COLUMN_BITMASK = 2L;
	public static final long HOMEPAGE_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Coleccion toModel(ColeccionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Coleccion model = new ColeccionImpl();

		model.setUuid(soapModel.getUuid());
		model.setGroupId(soapModel.getGroupId());
		model.setHomepage(soapModel.getHomepage());
		model.setTitulo(soapModel.getTitulo());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Coleccion> toModels(ColeccionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Coleccion> models = new ArrayList<Coleccion>(soapModels.length);

		for (ColeccionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.docs.datosGob.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.docs.datosGob.model.Coleccion"));

	public ColeccionModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _homepage;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setHomepage(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _homepage;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Coleccion.class;
	}

	@Override
	public String getModelClassName() {
		return Coleccion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("groupId", getGroupId());
		attributes.put("homepage", getHomepage());
		attributes.put("titulo", getTitulo());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		String homepage = (String)attributes.get("homepage");

		if (homepage != null) {
			setHomepage(homepage);
		}

		String titulo = (String)attributes.get("titulo");

		if (titulo != null) {
			setTitulo(titulo);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public String getHomepage() {
		if (_homepage == null) {
			return "";
		}
		else {
			return _homepage;
		}
	}

	@Override
	public void setHomepage(String homepage) {
		_homepage = homepage;
	}

	@JSON
	@Override
	public String getTitulo() {
		if (_titulo == null) {
			return "";
		}
		else {
			return _titulo;
		}
	}

	@Override
	public void setTitulo(String titulo) {
		_titulo = titulo;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Coleccion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Coleccion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ColeccionImpl coleccionImpl = new ColeccionImpl();

		coleccionImpl.setUuid(getUuid());
		coleccionImpl.setGroupId(getGroupId());
		coleccionImpl.setHomepage(getHomepage());
		coleccionImpl.setTitulo(getTitulo());

		coleccionImpl.resetOriginalValues();

		return coleccionImpl;
	}

	@Override
	public int compareTo(Coleccion coleccion) {
		String primaryKey = coleccion.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Coleccion)) {
			return false;
		}

		Coleccion coleccion = (Coleccion)obj;

		String primaryKey = coleccion.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ColeccionModelImpl coleccionModelImpl = this;

		coleccionModelImpl._originalUuid = coleccionModelImpl._uuid;

		coleccionModelImpl._originalGroupId = coleccionModelImpl._groupId;

		coleccionModelImpl._setOriginalGroupId = false;

		coleccionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Coleccion> toCacheModel() {
		ColeccionCacheModel coleccionCacheModel = new ColeccionCacheModel();

		coleccionCacheModel.uuid = getUuid();

		String uuid = coleccionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			coleccionCacheModel.uuid = null;
		}

		coleccionCacheModel.groupId = getGroupId();

		coleccionCacheModel.homepage = getHomepage();

		String homepage = coleccionCacheModel.homepage;

		if ((homepage != null) && (homepage.length() == 0)) {
			coleccionCacheModel.homepage = null;
		}

		coleccionCacheModel.titulo = getTitulo();

		String titulo = coleccionCacheModel.titulo;

		if ((titulo != null) && (titulo.length() == 0)) {
			coleccionCacheModel.titulo = null;
		}

		return coleccionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", homepage=");
		sb.append(getHomepage());
		sb.append(", titulo=");
		sb.append(getTitulo());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.liferay.docs.datosGob.model.Coleccion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>homepage</column-name><column-value><![CDATA[");
		sb.append(getHomepage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>titulo</column-name><column-value><![CDATA[");
		sb.append(getTitulo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Coleccion.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Coleccion.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private String _homepage;
	private String _titulo;
	private long _columnBitmask;
	private Coleccion _escapedModel;
}