/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.datosGob.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.docs.datosGob.model.Dataset;
import com.liferay.docs.datosGob.model.DatasetModel;
import com.liferay.docs.datosGob.model.DatasetSoap;

import com.liferay.petra.string.StringBundler;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Dataset service. Represents a row in the &quot;DB_Dataset&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link DatasetModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DatasetImpl}.
 * </p>
 *
 * @author liferay
 * @see DatasetImpl
 * @see Dataset
 * @see DatasetModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DatasetModelImpl extends BaseModelImpl<Dataset>
	implements DatasetModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dataset model instance should use the {@link Dataset} interface instead.
	 */
	public static final String TABLE_NAME = "DB_Dataset";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "datasetId", Types.VARCHAR },
			{ "groupId", Types.BIGINT },
			{ "homepage", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("datasetId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("homepage", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table DB_Dataset (uuid_ VARCHAR(75) null,datasetId VARCHAR(75) not null primary key,groupId LONG,homepage VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DB_Dataset";
	public static final String ORDER_BY_JPQL = " ORDER BY dataset.datasetId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DB_Dataset.datasetId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.docs.datosGob.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.docs.datosGob.model.Dataset"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.docs.datosGob.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.docs.datosGob.model.Dataset"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.docs.datosGob.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.docs.datosGob.model.Dataset"),
			true);
	public static final long GROUPID_COLUMN_BITMASK = 1L;
	public static final long HOMEPAGE_COLUMN_BITMASK = 2L;
	public static final long UUID_COLUMN_BITMASK = 4L;
	public static final long DATASETID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Dataset toModel(DatasetSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Dataset model = new DatasetImpl();

		model.setUuid(soapModel.getUuid());
		model.setDatasetId(soapModel.getDatasetId());
		model.setGroupId(soapModel.getGroupId());
		model.setHomepage(soapModel.getHomepage());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Dataset> toModels(DatasetSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Dataset> models = new ArrayList<Dataset>(soapModels.length);

		for (DatasetSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.docs.datosGob.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.docs.datosGob.model.Dataset"));

	public DatasetModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _datasetId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setDatasetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _datasetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Dataset.class;
	}

	@Override
	public String getModelClassName() {
		return Dataset.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("datasetId", getDatasetId());
		attributes.put("groupId", getGroupId());
		attributes.put("homepage", getHomepage());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		String datasetId = (String)attributes.get("datasetId");

		if (datasetId != null) {
			setDatasetId(datasetId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		String homepage = (String)attributes.get("homepage");

		if (homepage != null) {
			setHomepage(homepage);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public String getDatasetId() {
		if (_datasetId == null) {
			return "";
		}
		else {
			return _datasetId;
		}
	}

	@Override
	public void setDatasetId(String datasetId) {
		_datasetId = datasetId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public String getHomepage() {
		if (_homepage == null) {
			return "";
		}
		else {
			return _homepage;
		}
	}

	@Override
	public void setHomepage(String homepage) {
		_columnBitmask |= HOMEPAGE_COLUMN_BITMASK;

		if (_originalHomepage == null) {
			_originalHomepage = _homepage;
		}

		_homepage = homepage;
	}

	public String getOriginalHomepage() {
		return GetterUtil.getString(_originalHomepage);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Dataset toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Dataset)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DatasetImpl datasetImpl = new DatasetImpl();

		datasetImpl.setUuid(getUuid());
		datasetImpl.setDatasetId(getDatasetId());
		datasetImpl.setGroupId(getGroupId());
		datasetImpl.setHomepage(getHomepage());

		datasetImpl.resetOriginalValues();

		return datasetImpl;
	}

	@Override
	public int compareTo(Dataset dataset) {
		String primaryKey = dataset.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Dataset)) {
			return false;
		}

		Dataset dataset = (Dataset)obj;

		String primaryKey = dataset.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		DatasetModelImpl datasetModelImpl = this;

		datasetModelImpl._originalUuid = datasetModelImpl._uuid;

		datasetModelImpl._originalGroupId = datasetModelImpl._groupId;

		datasetModelImpl._setOriginalGroupId = false;

		datasetModelImpl._originalHomepage = datasetModelImpl._homepage;

		datasetModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Dataset> toCacheModel() {
		DatasetCacheModel datasetCacheModel = new DatasetCacheModel();

		datasetCacheModel.uuid = getUuid();

		String uuid = datasetCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			datasetCacheModel.uuid = null;
		}

		datasetCacheModel.datasetId = getDatasetId();

		String datasetId = datasetCacheModel.datasetId;

		if ((datasetId != null) && (datasetId.length() == 0)) {
			datasetCacheModel.datasetId = null;
		}

		datasetCacheModel.groupId = getGroupId();

		datasetCacheModel.homepage = getHomepage();

		String homepage = datasetCacheModel.homepage;

		if ((homepage != null) && (homepage.length() == 0)) {
			datasetCacheModel.homepage = null;
		}

		return datasetCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", datasetId=");
		sb.append(getDatasetId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", homepage=");
		sb.append(getHomepage());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.liferay.docs.datosGob.model.Dataset");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>datasetId</column-name><column-value><![CDATA[");
		sb.append(getDatasetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>homepage</column-name><column-value><![CDATA[");
		sb.append(getHomepage());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Dataset.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Dataset.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private String _datasetId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private String _homepage;
	private String _originalHomepage;
	private long _columnBitmask;
	private Dataset _escapedModel;
}