/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.datosGob.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Dataset service. Represents a row in the &quot;DB_Dataset&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.datosGob.model.impl.DatasetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.datosGob.model.impl.DatasetImpl}.
 * </p>
 *
 * @author liferay
 * @see Dataset
 * @see com.liferay.docs.datosGob.model.impl.DatasetImpl
 * @see com.liferay.docs.datosGob.model.impl.DatasetModelImpl
 * @generated
 */
@ProviderType
public interface DatasetModel extends BaseModel<Dataset> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dataset model instance should use the {@link Dataset} interface instead.
	 */

	/**
	 * Returns the primary key of this dataset.
	 *
	 * @return the primary key of this dataset
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this dataset.
	 *
	 * @param primaryKey the primary key of this dataset
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this dataset.
	 *
	 * @return the uuid of this dataset
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this dataset.
	 *
	 * @param uuid the uuid of this dataset
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the dataset ID of this dataset.
	 *
	 * @return the dataset ID of this dataset
	 */
	@AutoEscape
	public String getDatasetId();

	/**
	 * Sets the dataset ID of this dataset.
	 *
	 * @param datasetId the dataset ID of this dataset
	 */
	public void setDatasetId(String datasetId);

	/**
	 * Returns the group ID of this dataset.
	 *
	 * @return the group ID of this dataset
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dataset.
	 *
	 * @param groupId the group ID of this dataset
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the homepage of this dataset.
	 *
	 * @return the homepage of this dataset
	 */
	@AutoEscape
	public String getHomepage();

	/**
	 * Sets the homepage of this dataset.
	 *
	 * @param homepage the homepage of this dataset
	 */
	public void setHomepage(String homepage);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Dataset dataset);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Dataset> toCacheModel();

	@Override
	public Dataset toEscapedModel();

	@Override
	public Dataset toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}